name: Build epo.exe for multiple platforms

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build epo.exe on Windows
        run: |
          pyinstaller --onefile --name epo epo.py

      - name: Upload epo.exe as artifact
        uses: actions/upload-artifact@v4
        with:
          name: epo-executable-windows
          path: dist/epo.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build executable on Linux
        run: |
          pyinstaller --onefile --name epo epo.py

      - name: Upload epo executable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: epo-executable-linux
          path: dist/epo

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build executable on macOS
        run: |
          pyinstaller --onefile --name epo epo.py

      - name: Upload epo executable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: epo-executable-macos
          path: dist/epo
