name: Build epo.exe for multiple platforms

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build epo.exe on Windows
        run: |
          pyinstaller --onefile --name epo epo.py

      - name: Upload epo.exe as artifact
        uses: actions/upload-artifact@v4
        with:
          name: epo-executable-windows
          path: dist/epo.exe

      - name: Set up Git for commit
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
      
      - name: Pull latest changes from remote
        run: |
          git pull origin main
      
      - name: Add and commit built epo.exe
        run: |
          git add dist/epo.exe
          git commit -m "Add built epo.exe"
      
      - name: Push built epo.exe to repository
        run: |
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build executable on Linux
        run: |
          pyinstaller --onefile --name epo epo.py

      - name: Upload epo executable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: epo-executable-linux
          path: dist/epo

      - name: Set up Git for commit
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
      
      - name: Pull latest changes from remote
        run: |
          git pull origin main
      
      - name: Add and commit built epo on Linux
        run: |
          git add dist/epo
          git commit -m "Add built epo for Linux"
      
      - name: Push built epo to repository
        run: |
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build executable on macOS
        run: |
          pyinstaller --onefile --name epo epo.py

      - name: Upload epo executable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: epo-executable-macos
          path: dist/epo

      - name: Set up Git for commit
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
      
      - name: Pull latest changes from remote
        run: |
          git pull origin main
      
      - name: Add and commit built epo for macOS
        run: |
          git add dist/epo
          git commit -m "Add built epo for macOS"
      
      - name: Push built epo to repository
        run: |
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
